@baseUrl = https://coding-challenge-api.aerolab.co
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjA4NTNlZWRlOWNhYTAwMjFiMjhmNmQiLCJpYXQiOjE2NDQ3MTI5NDJ9.1YdkzdnKsK6nOzaduGlUd6jWjxdUNwk0wMTRv4niMGI

GET {{baseUrl}}/user/me HTTP/1.1
Authorization:Bearer {{token}}
Content-Type:application/json
Accept:application/json
